// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var recordingResponse = RecordingResponse.FromJson(jsonString);

namespace Brainz.Recording
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RecordingResponse
    {
        [JsonProperty("media")]
        public Media[] Media { get; set; }

        [JsonProperty("packaging-id")]
        public Guid PackagingId { get; set; }

        [JsonProperty("quality")]
        public string Quality { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("packaging")]
        public string Packaging { get; set; }

        [JsonProperty("release-events")]
        public ReleaseEvent[] ReleaseEvents { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("cover-art-archive")]
        public CoverArtArchive CoverArtArchive { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("asin")]
        public object Asin { get; set; }

        [JsonProperty("text-representation")]
        public TextRepresentation TextRepresentation { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("barcode")]
        public string Barcode { get; set; }

        [JsonProperty("status-id")]
        public Guid StatusId { get; set; }
    }

    public partial class CoverArtArchive
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("artwork")]
        public bool Artwork { get; set; }

        [JsonProperty("back")]
        public bool Back { get; set; }

        [JsonProperty("front")]
        public bool Front { get; set; }

        [JsonProperty("darkened")]
        public bool Darkened { get; set; }
    }

    public partial class Media
    {
        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("tracks")]
        public Track[] Tracks { get; set; }

        [JsonProperty("format-id")]
        public Guid FormatId { get; set; }

        [JsonProperty("position")]
        public long Position { get; set; }

        [JsonProperty("track-count")]
        public long TrackCount { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("track-offset")]
        public long TrackOffset { get; set; }
    }

    public partial class Track
    {
        [JsonProperty("position")]
        public long Position { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("recording")]
        public Recording Recording { get; set; }
    }

    public partial class Recording
    {
        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("video")]
        public bool Video { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }
    }

    public partial class ReleaseEvent
    {
        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("area")]
        public Area Area { get; set; }
    }

    public partial class Area
    {
        [JsonProperty("iso-3166-1-codes")]
        public string[] Iso31661Codes { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("sort-name")]
        public string SortName { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class TextRepresentation
    {
        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("script")]
        public string Script { get; set; }
    }
}