// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var releaseGroupResponse = ReleaseGroupResponse.FromJson(jsonString);

namespace Brainz.ReleaseGroup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ReleaseGroupResponse
    {
        [JsonProperty("release-groups")]
        public ReleaseGroup[] ReleaseGroups { get; set; }

        [JsonProperty("release-group-count")]
        public long ReleaseGroupCount { get; set; }

        [JsonProperty("release-group-offset")]
        public long ReleaseGroupOffset { get; set; }
    }

    public partial class ReleaseGroup
    {
        [JsonProperty("secondary-type-ids")]
        public Guid[] SecondaryTypeIds { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("first-release-date")]
        public string FirstReleaseDate { get; set; }

        [JsonProperty("primary-type-id")]
        public Guid PrimaryTypeId { get; set; }

        [JsonProperty("primary-type")]
        public PrimaryType PrimaryType { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("secondary-types")]
        public SecondaryType[] SecondaryTypes { get; set; }
    }

    // from the docs: nat, album, single, ep, compilation, soundtrack, spokenword, interview, audiobook, live, remix, other
    public enum PrimaryType { NAT, Album, Single, EP };

    public enum SecondaryType { Demo, Compilation, Soundtrack, SpokenWord, Interview, AudioBook, Live, Remix, Other };
}